In [1]:
import os
from src.module.database import oracle_import, oracle_export, oracle_execute
#os.environ

In [2]:
marketplace_mp = oracle_import("""select id_, userid, p_date from toki.MONGO_MINIPROGRAMUSERLOGS partition(p_202605)
     where MINIPROGRAMID = '6821b668840548dbe178eacb'""")

/workspaces/marketplace-stream-data-recommendation-engine/src/module/database.py:127: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_frame = pd.read_sql(query, engine)
2026-07-23 10:52:10.581 | INFO     | __main__:<module>:1 - Function oracle_import executed in: 1 min 20 sec

In [3]:
marketplace_mp["USERID"].unique().shape

(258604,)

In [4]:
marketplace_mp.tail()

                             ID_                    USERID    P_DATE
633632  6a1c5078982236d956e8040d  65afc92e5687245adfba3f93  20260531
633633  6a1c516cf081a0899db9ed8a  66d5712c98ce1d7839f29b29  20260531
633634  6a1c516ec54f01072f707b4a  655f4c21e22c5f4c8b76d1ad  20260531
633635  6a1c51d12091a9e894b4d1b2  65d39d6735ef84b89ee1f638  20260531
633636  6a1c528e6adb6e8a91d03110  60d5415041f18afccfbdc833  20260531

In [5]:
consumer_events = oracle_import("select * from toki.marketplace_consumer_EVENTS where p_date >='20260701'")

/workspaces/marketplace-stream-data-recommendation-engine/src/module/database.py:127: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_frame = pd.read_sql(query, engine)
2026-07-23 10:52:39.451 | INFO     | __main__:<module>:1 - Function oracle_import executed in: 20 sec 460 ms

In [6]:
customer_activities = oracle_import("select * from toki.marketplace_consumer_activities where p_date >='20260701'")

2026-07-23 10:54:19.229 | INFO     | __main__:<module>:1 - Function oracle_import executed in: 1 min 39 sec

In [7]:
customer_activities.head()

,ID_,ACTIVITYNAME,ACTIVITYDATA,CREATEDAT,UPDATEDAT,P_DATE
0,6a442142805151b025d9ff1d,cart-events,"{'cartId': '63b572a5119256f621a0c935', 'type':...",2026-07-01 04:04:18,2026-07-01 04:04:18,20260701
1,6a442142ce31add3c3475288,cart-events,"{'cartId': '5fb9457f58786d2fc4e4a6b5', 'type':...",2026-07-01 04:04:18,2026-07-01 04:04:18,20260701
2,6a442142ce31add3c347528a,cart-events,"{'cartId': '69a1cf749d7bf25a7dcdf8ad', 'type':...",2026-07-01 04:04:18,2026-07-01 04:04:18,20260701
3,6a442142ce31add3c347528c,cart-events,"{'cartId': '68d27a73ca4a9a5563b54e15', 'type':...",2026-07-01 04:04:18,2026-07-01 04:04:18,20260701
4,6a442142805151b025d9ff1f,cart-events,"{'cartId': '68d51739282d4349b9bd7681', 'type':...",2026-07-01 04:04:18,2026-07-01 04:04:18,20260701

In [8]:
customer_activities["ACTIVITYDATA"].values[0]

"{'cartId': '63b572a5119256f621a0c935', 'type': 'PRODUCT_MODIFIED', 'item': {'productId': '692e313c49a5eecb319a3f58', 'qty': 1, 'available': True, '_id': '69a302381449fddd66765d91'}, 'cart': {'_id': '69a1c0191449fddd6670fcc5', 'accountId': '63b572a5119256f621a0c935', 'items': [{'productId': '692e313c49a5eecb319a3f58', 'qty': 1, 'available': True, '_id': '69a302381449fddd66765d91'}, {'productId': '68febd519494859a95029a61', 'qty': 1, 'available': True, '_id': '69a54eac1449fddd66834326'}, {'productId': '68febd4c9494859a95029a58', 'qty': 1, 'available': True, '_id': '69a54eec1449fddd66834389'}], 'createdAt': '2026-02-27T16:02:33.965Z', 'updatedAt': '2026-06-30T20:04:18.220Z'}}"

In [9]:
import json
import ast

In [10]:
ast.literal_eval(customer_activities["ACTIVITYDATA"].values[0])

{'cartId': '63b572a5119256f621a0c935',
 'type': 'PRODUCT_MODIFIED',
 'item': {'productId': '692e313c49a5eecb319a3f58',
  'qty': 1,
  'available': True,
  '_id': '69a302381449fddd66765d91'},
 'cart': {'_id': '69a1c0191449fddd6670fcc5',
  'accountId': '63b572a5119256f621a0c935',
  'items': [{'productId': '692e313c49a5eecb319a3f58',
    'qty': 1,
    'available': True,
    '_id': '69a302381449fddd66765d91'},
   {'productId': '68febd519494859a95029a61',
    'qty': 1,
    'available': True,
    '_id': '69a54eac1449fddd66834326'},
   {'productId': '68febd4c9494859a95029a58',
    'qty': 1,
    'available': True,
    '_id': '69a54eec1449fddd66834389'}],
  'createdAt': '2026-02-27T16:02:33.965Z',
  'updatedAt': '2026-06-30T20:04:18.220Z'}}

In [11]:
from datetime import datetime, timedelta
snapshot_date = datetime.today().date()
snapshot_date = snapshot_date.strftime("%Y%m%d")

In [12]:
marketplace_products = oracle_import(f"select * from toki.marketplace_catalogue_products where SNAPSHOT_DATE >= to_date('{snapshot_date}', 'YYYYMMDD')")

/workspaces/marketplace-stream-data-recommendation-engine/src/module/database.py:127: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data_frame = pd.read_sql(query, engine)
2026-07-23 10:56:05.867 | INFO     | __main__:<module>:1 - Function oracle_import executed in: 1 min 46 sec

In [13]:
marketplace_products.head()

,ID_,GROUPID,PRODUCTID,STOREID,SKU,BRAND,STOCK,MAINPRICE,SALEPRICE,SALEPERC,...,ASSETS,TAXONOMY,URL_,TAXON,VARIANTS,HASGIFT,CREATEDAT,UPDATEDAT,PRODUCTSTATE,SNAPSHOT_DATE
0,6a2fe95b38713901eb69c0e4,4d9f7925-afa2-59bd-9218-a7b57d6664c2,6a0546b4109dd372dc9c088d,691aef5c2dbd3a51d50796cb,ELEC-EMS-4560X,ELECTROLUX,1,2199900,1899900,13.64,...,['https://imagedelivery.net/jUCGGlEY6TCUtkJb-F...,"[{'id': '69fbf9771e4213029f4e7d31', 'level': 0...",/6a0546b4109dd372dc9c088d,"{'id': '69fbf9771e4213029f4e7d31', 'label': 'П...",[],False,2026-06-15 20:00:25,2026-06-24 13:34:23,SETTLED,2026-07-23 00:03:26
1,6a2fe95b38713901eb69c0e5,23d1f426-a04f-5c2e-8ae0-473c1a223846,6a0bfc8e174bffd07037ed16,691aef5c2dbd3a51d50796cb,MI-AF-6B,XIAOMI,7,339900,339900,0,...,['https://imagedelivery.net/jUCGGlEY6TCUtkJb-F...,"[{'id': '69fb0b5b9d0fc72657c65255', 'level': 0...",/6a0bfc8e174bffd07037ed16,"{'id': '69fb0b5b9d0fc72657c65255', 'label': 'Т...",[],False,2026-06-15 20:00:25,2026-07-22 20:00:21,ARCHIVED,2026-07-23 00:03:26
2,6a2fe95b38713901eb69c105,0b0b48aa-3c52-585e-a6a5-f88a2270dd8a,6a206bdf61436204972e0030,691aef5c2dbd3a51d50796cb,MI-APRO55-26,XIAOMI,30,1699900,1699900,0,...,['https://imagedelivery.net/jUCGGlEY6TCUtkJb-F...,"[{'id': '674425c2b07fff9ff4a48d4c', 'level': 0...",/6a206bdf61436204972e0030,"{'id': '674425c2b07fff9ff4a48d4c', 'label': 'З...",[],False,2026-06-15 20:00:25,2026-07-22 14:00:19,SETTLED,2026-07-23 00:03:26
3,6a2fe95b38713901eb69c106,ab715b94-fc5c-55ec-8d13-730ba04fd6ae,6a22661c87e3e71b6da449c0,691aef5c2dbd3a51d50796cb,KONK-KG80-12L24B,KONKA,209,949900,699900,26.32,...,['https://imagedelivery.net/jUCGGlEY6TCUtkJb-F...,"[{'id': '69fb11b38c9f6a3289e6437c', 'level': 0...",/6a22661c87e3e71b6da449c0,"{'id': '69fb11b38c9f6a3289e6437c', 'label': 'У...",[],False,2026-06-15 20:00:25,2026-07-22 14:00:19,SETTLED,2026-07-23 00:03:26
4,6a3a519738713901eb69c12d,8e603728-99d3-50f5-852a-9939faa1dd23,6a309f86d46aca65f80843c5,6a2f8804c7f1cc040b589a3b,ANTM-3784_19B3,DYSON,1,2850000,2850000,0,...,['https://new.antmall.mn/images/detailed/45/an...,"[{'id': '69fb16a36712683b9c3f5b84', 'level': 0...",/6a309f86d46aca65f80843c5,"{'id': '69fb16a36712683b9c3f5b84', 'label': 'Ү...","[{'productId': '6a309f86d46aca65f80843c5', '_i...",False,2026-06-23 17:27:51,2026-07-22 17:24:05,SETTLED,2026-07-23 00:03:26

In [14]:
productid = '69fc469bab34c8d11412ec79'
marketplace_products[marketplace_products["PRODUCTID"] == productid]

,ID_,GROUPID,PRODUCTID,STOREID,SKU,BRAND,STOCK,MAINPRICE,SALEPRICE,SALEPERC,...,ASSETS,TAXONOMY,URL_,TAXON,VARIANTS,HASGIFT,CREATEDAT,UPDATEDAT,PRODUCTSTATE,SNAPSHOT_DATE
329,6a0b3d3b38713901eb69bc30,86280094-3bd8-58e3-a377-b7f51bd157a2,69fc469bab34c8d11412ec79,6912d444458a4a2f9ca10060,SF321LF0,ROWENTA,1,199900,199900,0,...,['https://cdnp.cody.mn/spree/images/3431242/la...,"[{'id': '69fb16a36712683b9c3f5b84', 'level': 0...",/69fc469bab34c8d11412ec79,"{'id': '69fb16a36712683b9c3f5b84', 'label': 'Ү...","[{'productId': '69fc469bab34c8d11412ec79', '_i...",False,2026-05-19 00:24:26,2026-07-23 00:00:22,ARCHIVED,2026-07-23 00:03:26

In [15]:
consumer_events.shape

(302894, 11)

In [16]:
consumer_events.tail()

,ID_,EVENTNAME,EVENTVALUE,ACCOUNTID,SESSIONID,TIMESTAMP_,USERAGENT,URL_,CREATEDAT,UPDATEDAT,P_DATE
302889,6a60eaa9ce31add3c35884b2,taxon_click,{'taxon': {'label': 'Гал тогоо'}},6062bbf1855bbb3d19d02846,aMLgpECt-uBy_VgLZ2FH9czXYJxyspeg,2026-07-22T16:07:05.917Z,Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like M...,https://marketplace.toki.mn/home/67442509f47e8...,2026-07-23 00:07:05,2026-07-23 00:07:05,20260723
302890,6a60eaaa4aeec353171e659e,taxon_click,{'taxon': {'label': 'Гал тогоо'}},6062bbf1855bbb3d19d02846,aMLgpECt-uBy_VgLZ2FH9czXYJxyspeg,2026-07-22T16:07:06.108Z,Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like M...,https://marketplace.toki.mn/home/67442509f47e8...,2026-07-23 00:07:06,2026-07-23 00:07:06,20260723
302891,6a60eaaa4229463e57f43cd2,taxon_click,{'taxon': {'label': 'Гал тогоо'}},6062bbf1855bbb3d19d02846,aMLgpECt-uBy_VgLZ2FH9czXYJxyspeg,2026-07-22T16:07:06.311Z,Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like M...,https://marketplace.toki.mn/home/67442509f47e8...,2026-07-23 00:07:06,2026-07-23 00:07:06,20260723
302892,6a60eaaa805151b025eb34d3,taxon_click,{'taxon': {'label': 'Гал тогоо'}},6062bbf1855bbb3d19d02846,aMLgpECt-uBy_VgLZ2FH9czXYJxyspeg,2026-07-22T16:07:06.483Z,Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like M...,https://marketplace.toki.mn/home/67442509f47e8...,2026-07-23 00:07:06,2026-07-23 00:07:06,20260723
302893,6a60eaaa420fe633e03ed1e0,taxon_click,{'taxon': {'label': 'Гал тогоо'}},6062bbf1855bbb3d19d02846,aMLgpECt-uBy_VgLZ2FH9czXYJxyspeg,2026-07-22T16:07:06.668Z,Mozilla/5.0 (iPhone; CPU iPhone OS 18_5 like M...,https://marketplace.toki.mn/home/67442509f47e8...,2026-07-23 00:07:06,2026-07-23 00:07:06,20260723

In [17]:
consumer_events.head(2)

,ID_,EVENTNAME,EVENTVALUE,ACCOUNTID,SESSIONID,TIMESTAMP_,USERAGENT,URL_,CREATEDAT,UPDATEDAT,P_DATE
0,6a44ce39ce31add3c347e3d6,product_click,"{'productIds': ['69fc469bab34c8d11412ec79'], '...",66fbc5824e022311128232ae,jPAaTyDWFjD1JsHyR0ux3hewNYRvNvRy,2026-07-01T08:21:23.894Z,Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like M...,https://marketplace.toki.mn/home/69f326e4f996d...,2026-07-01 16:22:17,2026-07-01 16:22:17,20260701
1,6a44ce3b420fe633e02e2e78,taxon_click,{'taxon': {'label': 'Гар утас'}},5ff870ee4f636263bd482270,2xI3rxpGJbBOeY4vnY_1EBSkTuAL8Pf9,2026-07-01T08:22:19.413Z,Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like M...,https://marketplace.toki.mn/home,2026-07-01 16:22:19,2026-07-01 16:22:19,20260701

In [18]:
consumer_events.groupby("EVENTNAME").count()

,ID_,EVENTVALUE,ACCOUNTID,SESSIONID,TIMESTAMP_,USERAGENT,URL_,CREATEDAT,UPDATEDAT,P_DATE
EVENTNAME,,,,,,,,,,
product_click,133868,133868,133868,132798,133868,133868,133868,133868,133868,133868
taxon_click,169026,165120,169026,167699,169026,169026,169026,169026,169026,169026

In [34]:
consumer_events.head(2).to_json(orient = 'records')

/tmp/ipykernel_3013165/4066390533.py:1: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  consumer_events.head(2).to_json(orient = 'records')

'[{"ID_":"6a44ce39ce31add3c347e3d6","EVENTNAME":"product_click","EVENTVALUE":"{\'productIds\': [\'69fc469bab34c8d11412ec79\'], \'taxon\': {\'label\': \'\\u04ae\\u0441\\u043d\\u0438\\u0439 \\u0445\\u044d\\u0440\\u044d\\u0433\\u0441\\u044d\\u043b\'}}","ACCOUNTID":"66fbc5824e022311128232ae","SESSIONID":"jPAaTyDWFjD1JsHyR0ux3hewNYRvNvRy","TIMESTAMP_":"2026-07-01T08:21:23.894Z","USERAGENT":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Mobile\\/15E148","URL_":"https:\\/\\/marketplace.toki.mn\\/home\\/69f326e4f996d4fdbd2ade89\\/69fb16a36712683b9c3f5b84","CREATEDAT":1782922937000,"UPDATEDAT":1782922937000,"P_DATE":"20260701"},{"ID_":"6a44ce3b420fe633e02e2e78","EVENTNAME":"taxon_click","EVENTVALUE":"{\'taxon\': {\'label\': \'\\u0413\\u0430\\u0440 \\u0443\\u0442\\u0430\\u0441\'}}","ACCOUNTID":"5ff870ee4f636263bd482270","SESSIONID":"2xI3rxpGJbBOeY4vnY_1EBSkTuAL8Pf9","TIMESTAMP_":"2026-07-01T08:22:19.413Z","USERAGENT":"Mozilla\\/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit\\/605.1.15 (KHTML, like Gecko) Mobile\\/15E148","URL_":"https:\\/\\/marketplace.toki.mn\\/home","CREATEDAT":1782922939000,"UPDATEDAT":1782922939000,"P_DATE":"20260701"}]'

In [19]:
consumer_events[consumer_events["EVENTNAME"] == "taxon_click"]["EVENTVALUE"].unique()

<StringArray>
[                                                                                                                                '{'taxon': {'label': 'Гар утас'}}',
                                                                                                                                   '{'taxon': {'label': 'Зурагт'}}',
                                                                                                                          '{'taxon': {'label': 'Тренд технологи'}}',
                                                                                                                                '{'taxon': {'label': 'Гал тогоо'}}',
                                                                                                                                 '{'taxon': {'label': 'Гэр ахуй'}}',
                                                                                                                              '{'taxon': {'label': 'Мик, спикер'}}',
                                                                                                                                                                nan,
                                                                                                                              '{'taxon': {'label': 'Ухаалаг Цаг'}}',
                                                                                                                                   '{'taxon': {'label': 'Таблет'}}',
                                                                                                                        '{'taxon': {'label': 'Дагалдах хэрэгсэл'}}',
 ...
 '{'productIds': ['67f8684d1ca4873792406dee', '68b7ee190bcb0200c3e8d801', '681c2198941590a9221439a2', '67f8686d941590a9221302d8'], 'taxon': {'label': 'Гар утас'}}',
                                                                                     '{'productIds': ['6a0c50f2cb69d09071673641'], 'taxon': {'label': 'Стандарт'}}',
                                                                                  '{'productIds': ['67a9514cdab916e2e00e3a0e'], 'taxon': {'label': 'Ухаалаг Цаг'}}',
                                                                             '{'productIds': ['6a05469a109dd372dc9bfbd0'], 'taxon': {'label': 'Суурин компьютер'}}',
                                                                                       '{'productIds': ['6a0546ad109dd372dc9c0431'], 'taxon': {'label': 'Дэлгэц'}}',
                                                      '{'productIds': ['6a309f8cd46aca65f8084455', '6a309f8cd46aca65f8084455'], 'taxon': {'label': 'Тоос сорогч'}}',
                                                                                       '{'productIds': ['6a0546a4109dd372dc9bffdb'], 'taxon': {'label': 'Плитка'}}',
                          '{'productIds': ['68d9dac263d257398caccc84', '68d9dac163d257398caccc81', '68d9dac063d257398caccc7e'], 'taxon': {'label': 'Ухаалаг Цаг'}}',
                                                                                       '{'productIds': ['6936a1a31381e00acba3c774'], 'taxon': {'label': 'Зурагт'}}',
 '{'productIds': ['699e695bfd48a0ea61c5e445', '699e6966fd48a0ea61c5e446', '699e6975fd48a0ea61c5e447', '699e693efd48a0ea61c5e444'], 'taxon': {'label': 'Гар утас'}}']
Length: 490, dtype: str

In [20]:
consumer_events[consumer_events["ACCOUNTID"] == '6a5e47214aeec353171ccaa0']

Empty DataFrame
Columns: [ID_, EVENTNAME, EVENTVALUE, ACCOUNTID, SESSIONID, TIMESTAMP_, USERAGENT, URL_, CREATEDAT, UPDATEDAT, P_DATE]
Index: []

In [21]:
consumer_events[consumer_events["SESSIONID"] == "jPAaTyDWFjD1JsHyR0ux3hewNYRvNvRy"]["EVENTVALUE"].values

<StringArray>
['{'productIds': ['69fc469bab34c8d11412ec79'], 'taxon': {'label': 'Үсний хэрэгсэл'}}',
 '{'productIds': ['6a309f8bd46aca65f808443d'], 'taxon': {'label': 'Үсний хэрэгсэл'}}',
 '{'productIds': ['6a052b7de66ad55426cacf70'], 'taxon': {'label': 'Үсний хэрэгсэл'}}',
                                                '{'taxon': {'label': 'Мик, спикер'}}',
         '{'productIds': ['69f9b680ce8b92727bb248a0'], 'taxon': {'label': 'Спикер'}}',
         '{'productIds': ['6a2bf50230ec49e38af99da7'], 'taxon': {'label': 'Спикер'}}',
                                             '{'taxon': {'label': 'Үсний хэрэгсэл'}}']
Length: 7, dtype: str

In [22]:
customer_activities["ACTIVITYDATA"].values[0]

"{'cartId': '63b572a5119256f621a0c935', 'type': 'PRODUCT_MODIFIED', 'item': {'productId': '692e313c49a5eecb319a3f58', 'qty': 1, 'available': True, '_id': '69a302381449fddd66765d91'}, 'cart': {'_id': '69a1c0191449fddd6670fcc5', 'accountId': '63b572a5119256f621a0c935', 'items': [{'productId': '692e313c49a5eecb319a3f58', 'qty': 1, 'available': True, '_id': '69a302381449fddd66765d91'}, {'productId': '68febd519494859a95029a61', 'qty': 1, 'available': True, '_id': '69a54eac1449fddd66834326'}, {'productId': '68febd4c9494859a95029a58', 'qty': 1, 'available': True, '_id': '69a54eec1449fddd66834389'}], 'createdAt': '2026-02-27T16:02:33.965Z', 'updatedAt': '2026-06-30T20:04:18.220Z'}}"

In [23]:
customer_activities["ACTIVITYDATA"].values[2]

"{'cartId': '69a1cf749d7bf25a7dcdf8ad', 'type': 'PRODUCT_MODIFIED', 'item': {'productId': '68d3cd51d36b9be827b44e3c', 'qty': 1, 'available': True, '_id': '6a3e98b19bd8f5a236d7ee4e'}, 'cart': {'_id': '69a1d17e1449fddd6672c3e0', 'accountId': '69a1cf749d7bf25a7dcdf8ad', 'items': [{'productId': '68d3cd51d36b9be827b44e3c', 'qty': 1, 'available': True, '_id': '6a3e98b19bd8f5a236d7ee4e'}], 'createdAt': '2026-02-27T17:16:46.492Z', 'updatedAt': '2026-06-30T20:04:18.234Z'}}"

In [24]:
customer_activities["ACTIVITYNAME"].unique()

<StringArray>
['cart-events', 'limit-events', 'order-events', 'wishlist-events']
Length: 4, dtype: str

In [25]:
customer_activities.groupby(["ACTIVITYNAME"]).count()

                     ID_  ACTIVITYDATA  CREATEDAT  UPDATEDAT   P_DATE
ACTIVITYNAME
cart-events      2536718       2536718    2536718    2536718  2536718
limit-events       71346         71346      71346      71346    71346
order-events       13501         13501      13501      13501    13501
wishlist-events     1810          1810       1810       1810     1810

In [26]:
customer_activities[customer_activities["ACTIVITYNAME"]== 'cart-events'].head()["ACTIVITYDATA"].values[4]

"{'cartId': '68d51739282d4349b9bd7681', 'type': 'PRODUCT_MODIFIED', 'item': {'productId': '68d3cd51d36b9be827b44e3c', 'qty': 1, 'available': True, '_id': '6a3ab17ace94f86945bf6201'}, 'cart': {'_id': '69a250a11449fddd6672e579', 'accountId': '68d51739282d4349b9bd7681', 'items': [{'productId': '68d3cd51d36b9be827b44e3c', 'qty': 1, 'available': True, '_id': '6a3ab17ace94f86945bf6201'}], 'createdAt': '2026-02-28T02:19:13.501Z', 'updatedAt': '2026-06-30T20:04:18.250Z'}}"

In [27]:
customer_activities["ACTIVITYDATA"].values[0]

"{'cartId': '63b572a5119256f621a0c935', 'type': 'PRODUCT_MODIFIED', 'item': {'productId': '692e313c49a5eecb319a3f58', 'qty': 1, 'available': True, '_id': '69a302381449fddd66765d91'}, 'cart': {'_id': '69a1c0191449fddd6670fcc5', 'accountId': '63b572a5119256f621a0c935', 'items': [{'productId': '692e313c49a5eecb319a3f58', 'qty': 1, 'available': True, '_id': '69a302381449fddd66765d91'}, {'productId': '68febd519494859a95029a61', 'qty': 1, 'available': True, '_id': '69a54eac1449fddd66834326'}, {'productId': '68febd4c9494859a95029a58', 'qty': 1, 'available': True, '_id': '69a54eec1449fddd66834389'}], 'createdAt': '2026-02-27T16:02:33.965Z', 'updatedAt': '2026-06-30T20:04:18.220Z'}}"

In [28]:
# there 4 events that could potentially be used to track user activity: "view_product"
# limit-events - user checked the lease limit
# order-events - user placed an order or completed an order
# wishlist-events - user added a product to their wishlist
# card-events added card or removed card, modified in the cards etc events,

In [29]:
from src.database import pgsql_import
master_catalog_profile = pgsql_import("select * from marketplace_catalog_data_extended_version3")

In [35]:
import pandas as pd
pd.set_option("display.max_columns", 100)

In [36]:
master_catalog_profile.head(2)

,carried_located_in,main_category,sub_category,product_category,exact_product_category,manufacturer,generic_name,actual_product,size,power_consumption,year,specifications,sku,connectivity,stock,price,dimensions,index,product_id,shop_name,discount,main_option,details,url_link,keywords,best_used_for,premium_grade,price_range,insurance,delivery,taxon_id,taxon_name,description,best_used_for_detail,taxondict,prompt_,created_at,colors,image_list,images,mainoption,data_relation_map,color,image,productstate,createdat,updatedat,productmeta,saleprice,image_urls,details_translation,group_id
0,Living Room,Electronics,Televisions,Mini LED QLED 4K TVs,Sony 85XR50 85-inch Mini LED QLED 4K HDR Googl...,SONY,Smart Television,Mini LED QLED 4K HDR Google 85 inch tv /SONY-K...,85 inches,,2026,"{""resolution"": ""UHD 4K 3840x2160p"", ""processor...",SONY-K-85XR50,"{""wifi"": ""Yes"", ""bluetooth"": ""Yes"", ""hdmi"": ""4...",2,11999900 MNT,Without stand: 1891 x 1085 x 492 mm; With stan...,shop_0_1772709420,6968a70895de95f954a9a16c,BSB Electronics,"{""regular_price"": ""12999900 MNT"", ""sale_price""...","{""screen-size"": ""85inch"", ""resolution"": ""3840x...",85-inch Sony Mini LED QLED 4K HDR Google TV wi...,https://imagedelivery.net/jUCGGlEY6TCUtkJb-Fl1...,"[""Sony TV"", ""85 inch TV"", ""Mini LED"", ""QLED"", ...",Entertainment,premium,luxury,,"Pickup, Shipping",674425c2b07fff9ff4a48d4c,tv,Screen size: 85 inch Resolution: UHD 4K 3840x2...,Optimized for home entertainment and streaming...,NaN,"{""role"": ""user"", ""content"": ""product index : 0...",2026-03-05 19:17:48.739441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9769a9ad-9471-5347-abf4-c920d69a0e3e
1,Living Room,Electronics,Televisions,4K UHD TVs,Full Array LED 4K HDR Smart TV,Panasonic,Smart Television,Panasonic TH-75NX900,75 inch,,2026,"{""screen_type"": ""Full Array LED"", ""resolution""...",PANA-TH-75NX900M,"{""wifi"": ""Yes"", ""bluetooth"": ""Bluetooth 5.1"", ...",1,4599900 MNT,1675 x 1041 x 363 mm,shop_1_1772709420,6968a70895de95f954a9a16f,BSB Electronics,"{""regular_price"": ""5499900 MNT"", ""sale_price"":...","{""screen-size"": ""75 inch"", ""resolution"": ""3840...",PRODUCTSTATE: ARCHIVED; SYNCSTATE: SYNCED; CRE...,https://imagedelivery.net/jUCGGlEY6TCUtkJb-Fl1...,"[""Panasonic"", ""Panasonic TH-75NX900"", ""75 inch...",Entertainment,premium,high-end,,Pickup,674425c2b07fff9ff4a48d4c,tv,"Screen size: 75 inch, 1675mm Screen: Full Arra...",Ideal for home entertainment and streaming (mo...,NaN,"{""role"": ""user"", ""content"": ""product index : 1...",2026-03-05 19:18:43.058787,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,eae2fd2c-1c51-56f4-a7ec-7561dbfd11e9

In [31]:
master_catalog_profile.tail(2).to_json(orient="records")

'[{"carried_located_in":"Home","main_category":"Home Appliances","sub_category":"Vacuum Cleaners","product_category":"Cordless Vacuum Cleaners","exact_product_category":"Dyson V15s Detect Submarine Complete","manufacturer":"DYSON","generic_name":"Vacuum Cleaner","actual_product":"Dyson V15s Detect Submarine\\u2122 Complete","size":"4.1 kg","power_consumption":"","year":"0","specifications":"{\\"suction_power\\": \\"240 AW\\", \\"runtime\\": \\"60 minutes\\", \\"charging_time\\": \\"4.5 hours\\", \\"filter\\": \\"Whole-machine HEPA\\", \\"cleaning_type\\": \\"dry and wet\\", \\"dust_detection\\": \\"Dust Detect sensor\\", \\"display\\": \\"LCD\\", \\"head_type\\": \\"Submarine wet roller head\\", \\"light\\": \\"Fluffy Optic laser\\"}","sku":"ANTM-3193","connectivity":"{}","stock":"4","price":"4100000 MNT","dimensions":"","index":"shop_49_1782115641","product_id":"6a309f8bd46aca65f8084431","shop_name":"ANTMALL","discount":"{}","main_option":"{}","details":"Cordless vacuum cleaner with wet and dry cleaning capability, HEPA filtration, dust detection sensor, and LCD display. Includes Submarine wet roller head and Fluffy Optic laser light for detecting hidden dust.","url_link":"https:\\/\\/new.antmall.mn\\/images\\/detailed\\/43\\/ant_img_69eaed2224ece5.23133691.jpg","keywords":"[\\"Dyson V15s\\", \\"cordless vacuum\\", \\"wet and dry vacuum\\", \\"HEPA vacuum\\", \\"Submarine\\", \\"ANTMALL\\"]","best_used_for":"Cleaning","premium_grade":"premium","price_range":"high-end","insurance":"","delivery":"","taxon_id":"69fb126eae2e0da5c8bca3a0","taxon_name":"household-appliances-multi-purpose-vacuum","description":"Dyson V15s Detect Submarine Complete \\u043d\\u044c \\u0445\\u04af\\u0447\\u0438\\u0440\\u0445\\u044d\\u0433 cordless vacuum \\u0431\\u04e9\\u0433\\u04e9\\u04e9\\u0434 \\u043d\\u044d\\u0433 \\u0442\\u04e9\\u0445\\u04e9\\u04e9\\u0440\\u04e9\\u043c\\u0436\\u04e9\\u04e9\\u0440 \\u0445\\u0443\\u0443\\u0440\\u0430\\u0439 \\u0441\\u043e\\u0440\\u043e\\u0445 + \\u0448\\u0430\\u043b \\u0443\\u0433\\u0430\\u0430\\u0445 (wet cleaning) \\u0431\\u043e\\u043b\\u043e\\u043c\\u0436\\u0442\\u043e\\u0439, HEPA \\u0448\\u04af\\u04af\\u043b\\u0442\\u04af\\u04af\\u0440 \\u0431\\u043e\\u043b\\u043e\\u043d \\u0443\\u0445\\u0430\\u0430\\u043b\\u0430\\u0433 dust detection-\\u0442\\u044d\\u0439 premium \\u0446\\u044d\\u0432\\u044d\\u0440\\u043b\\u044d\\u0433\\u044d\\u044d\\u043d\\u0438\\u0439 \\u0442\\u04e9\\u0445\\u04e9\\u04e9\\u0440\\u04e9\\u043c\\u0436 \\u044e\\u043c. \\u0413\\u043e\\u043b \\u043e\\u043d\\u0446\\u043b\\u043e\\u0433\\u0443\\u0443\\u0434 Submarine\\u2122 wet roller head - \\u0448\\u0430\\u043b \\u0443\\u0433\\u0430\\u0430\\u0445, \\u043d\\u043e\\u0439\\u0442\\u043e\\u043d \\u0446\\u044d\\u0432\\u044d\\u0440\\u043b\\u044d\\u0433\\u044d\\u044d Fluffy Optic\\u2122 \\u043b\\u0430\\u0437\\u0435\\u0440 \\u0433\\u044d\\u0440\\u044d\\u043b \\u2013 \\u043d\\u04af\\u0434\\u044d\\u043d\\u0434 \\u0445\\u0430\\u0440\\u0430\\u0433\\u0434\\u0430\\u0445\\u0433\\u04af\\u0439 \\u0442\\u043e\\u043e\\u0441\\u044b\\u0433 \\u0438\\u043b\\u0440\\u04af\\u04af\\u043b\\u043d\\u044d HEPA filtration (sealed system) \\u2013 \\u043c\\u0430\\u0448 \\u0436\\u0438\\u0436\\u0438\\u0433 \\u0442\\u043e\\u043e\\u0441\\u043e\\u043d\\u0446\\u0440\\u044b\\u0433 99%+ \\u0445\\u04af\\u0440\\u0442\\u044d\\u043b \\u0448\\u04af\\u04af\\u043d\\u044d Dust Detect sensor + LCD \\u0434\\u044d\\u043b\\u0433\\u044d\\u0446 \\u2013 \\u0442\\u043e\\u043e\\u0441 \\u0445\\u044d\\u043c\\u0436\\u0438\\u0436, \\u0431\\u043e\\u0434\\u0438\\u0442 \\u0446\\u0430\\u0433\\u0438\\u0439\\u043d \\u043c\\u044d\\u0434\\u044d\\u044d\\u043b\\u044d\\u043b \\u0445\\u0430\\u0440\\u0443\\u0443\\u043b\\u043d\\u0430 \\u04ae\\u0437\\u04af\\u04af\\u043b\\u044d\\u043b\\u0442\\u04af\\u04af\\u0434 \\u0417\\u0430\\u0433\\u0432\\u0430\\u0440: Dyson V15s Detect Submarine Complete \\u0421\\u043e\\u0440\\u043e\\u0445 \\u0445\\u04af\\u0447: 240 AW \\u0445\\u04af\\u0440\\u0442\\u044d\\u043b \\u0410\\u0436\\u0438\\u043b\\u043b\\u0430\\u0445 \\u0445\\u0443\\u0433\\u0430\\u0446\\u0430\\u0430: ~60 \\u043c\\u0438\\u043d\\u0443\\u0442 \\u0426\\u044d\\u043d\\u044d\\u0433\\u043b\\u044d\\u0445 \\u0445\\u0443\\u0433\\u0430\\u0446\\u0430\\u0430: ~4.5 \\u0446\\u0430\\u0433 \\u0416\\u0438\\u043d: ~4.1 \\u043a\\u0433 \\u043e\\u0440\\u0447\\u0438\\u043c \\u0428\\u04af\\u04af\\u043b\\u0442\\u04af\\u04af\\u0440: Whole-machine HEPA","best_used_for_detail":"","taxondict":null,"prompt_":"{\\"role\\": \\"user\\", \\"content\\": \\"product index : 49,\\\\n\'\'\'{\'PRODUCT_ID\': \'6a309f8bd46aca65f8084431\', \'ANTMALLPRODUCTID\': 35274, \'NAME\': \'Dyson V15s Detect Submarine\\u2122 Complete\', \'MAINPRICE\': 4100000, \'SALEPRICE\': 4100000.0, \'SKU\': \'ANTM-3193\', \'STOCK\': 4, \'IMAGE\': \'https:\\/\\/new.antmall.mn\\/images\\/detailed\\/43\\/ant_img_69eaed2224ece5.23133691.jpg\', \'IMAGES\': [\'https:\\/\\/new.antmall.mn\\/images\\/detailed\\/43\\/ant_img_69eaed2224ece5.23133691.jpg\', \'https:\\/\\/new.antmall.mn\\/images\\/detailed\\/43\\/ant_img_69eaed22747de8.66164692.jpg\', \'https:\\/\\/new.antmall.mn\\/images\\/detailed\\/43\\/ant_img_69eaed227d3db2.62889967.jpg\', \'https:\\/\\/new.antmall.mn\\/images\\/detailed\\/43\\/ant_img_69eaed22848003.69577942.jpg\', \'https:\\/\\/new.antmall.mn\\/images\\/detailed\\/43\\/ant_img_69eaed228b9270.60005105.jpg\', \'https:\\/\\/new.antmall.mn\\/images\\/detailed\\/43\\/ant_img_69eaed229314d1.34854429.jpg\', \'https:\\/\\/new.antmall.mn\\/images\\/detailed\\/43\\/ant_img_69eaed229a3407.67689000.jpg\'], \'SYNCSTATE\': \'SYNCED\', \'PRODUCTSTATE\': \'MODIFIED\', \'DESCRIPTION\': \'Dyson V15s Detect Submarine Complete \\u043d\\u044c \\u0445\\u04af\\u0447\\u0438\\u0440\\u0445\\u044d\\u0433 cordless vacuum \\u0431\\u04e9\\u0433\\u04e9\\u04e9\\u0434 \\u043d\\u044d\\u0433 \\u0442\\u04e9\\u0445\\u04e9\\u04e9\\u0440\\u04e9\\u043c\\u0436\\u04e9\\u04e9\\u0440 \\u0445\\u0443\\u0443\\u0440\\u0430\\u0439 \\u0441\\u043e\\u0440\\u043e\\u0445 + \\u0448\\u0430\\u043b \\u0443\\u0433\\u0430\\u0430\\u0445 (wet cleaning) \\u0431\\u043e\\u043b\\u043e\\u043c\\u0436\\u0442\\u043e\\u0439, HEPA \\u0448\\u04af\\u04af\\u043b\\u0442\\u04af\\u04af\\u0440 \\u0431\\u043e\\u043b\\u043e\\u043d \\u0443\\u0445\\u0430\\u0430\\u043b\\u0430\\u0433 dust detection-\\u0442\\u044d\\u0439 premium \\u0446\\u044d\\u0432\\u044d\\u0440\\u043b\\u044d\\u0433\\u044d\\u044d\\u043d\\u0438\\u0439 \\u0442\\u04e9\\u0445\\u04e9\\u04e9\\u0440\\u04e9\\u043c\\u0436 \\u044e\\u043c. \\u0413\\u043e\\u043b \\u043e\\u043d\\u0446\\u043b\\u043e\\u0433\\u0443\\u0443\\u0434 Submarine\\u2122 wet roller head - \\u0448\\u0430\\u043b \\u0443\\u0433\\u0430\\u0430\\u0445, \\u043d\\u043e\\u0439\\u0442\\u043e\\u043d \\u0446\\u044d\\u0432\\u044d\\u0440\\u043b\\u044d\\u0433\\u044d\\u044d Fluffy Optic\\u2122 \\u043b\\u0430\\u0437\\u0435\\u0440 \\u0433\\u044d\\u0440\\u044d\\u043b \\u2013 \\u043d\\u04af\\u0434\\u044d\\u043d\\u0434 \\u0445\\u0430\\u0440\\u0430\\u0433\\u0434\\u0430\\u0445\\u0433\\u04af\\u0439 \\u0442\\u043e\\u043e\\u0441\\u044b\\u0433 \\u0438\\u043b\\u0440\\u04af\\u04af\\u043b\\u043d\\u044d HEPA filtration (sealed system) \\u2013 \\u043c\\u0430\\u0448 \\u0436\\u0438\\u0436\\u0438\\u0433 \\u0442\\u043e\\u043e\\u0441\\u043e\\u043d\\u0446\\u0440\\u044b\\u0433 99%+ \\u0445\\u04af\\u0440\\u0442\\u044d\\u043b \\u0448\\u04af\\u04af\\u043d\\u044d Dust Detect sensor + LCD \\u0434\\u044d\\u043b\\u0433\\u044d\\u0446 \\u2013 \\u0442\\u043e\\u043e\\u0441 \\u0445\\u044d\\u043c\\u0436\\u0438\\u0436, \\u0431\\u043e\\u0434\\u0438\\u0442 \\u0446\\u0430\\u0433\\u0438\\u0439\\u043d \\u043c\\u044d\\u0434\\u044d\\u044d\\u043b\\u044d\\u043b \\u0445\\u0430\\u0440\\u0443\\u0443\\u043b\\u043d\\u0430 \\u04ae\\u0437\\u04af\\u04af\\u043b\\u044d\\u043b\\u0442\\u04af\\u04af\\u0434 \\u0417\\u0430\\u0433\\u0432\\u0430\\u0440: Dyson V15s Detect Submarine Complete \\u0421\\u043e\\u0440\\u043e\\u0445 \\u0445\\u04af\\u0447: 240 AW \\u0445\\u04af\\u0440\\u0442\\u044d\\u043b \\u0410\\u0436\\u0438\\u043b\\u043b\\u0430\\u0445 \\u0445\\u0443\\u0433\\u0430\\u0446\\u0430\\u0430: ~60 \\u043c\\u0438\\u043d\\u0443\\u0442 \\u0426\\u044d\\u043d\\u044d\\u0433\\u043b\\u044d\\u0445 \\u0445\\u0443\\u0433\\u0430\\u0446\\u0430\\u0430: ~4.5 \\u0446\\u0430\\u0433 \\u0416\\u0438\\u043d: ~4.1 \\u043a\\u0433 \\u043e\\u0440\\u0447\\u0438\\u043c \\u0428\\u04af\\u04af\\u043b\\u0442\\u04af\\u04af\\u0440: Whole-machine HEPA\', \'VARIANTS\': [35274], \'CREATEDAT\': \'2026-06-16T00:57:47.172Z\', \'UPDATEDAT\': \'2026-06-22T07:58:37.502Z\', \'CHECKSUM\': \'123\', \'BRAND\': \'DYSON\', \'SYNCEDAT\': \'2026-06-22T07:58:27.661Z\', \'PROPERTY\': nan, \'SHOP_NAME\': \'ANTMALL\'}\'\'\'\\"}","created_at":"2026-06-22 16:10:47.009290","colors":null,"image_list":null,"images":null,"mainoption":null,"data_relation_map":null,"color":null,"image":null,"productstate":null,"createdat":null,"updatedat":null,"productmeta":null,"saleprice":null,"image_urls":null,"details_translation":null,"group_id":"7f4f21c9-4073-5463-90f2-21ea124222e8"},{"carried_located_in":"Gaming Room","main_category":"Electronics","sub_category":"Gaming","product_category":"Racing Wheels & Pedals","exact_product_category":"Wired Racing Wheel and Pedal Set","manufacturer":"Thrustmaster","generic_name":"Racing Wheel Controller","actual_product":"Thrustmaster T-GT II Wired Wheel And Pedals Set","size":"","power_consumption":"","year":"","specifications":"{\\"connectivity\\": \\"Wired\\", \\"compatibility\\": [\\"PC\\", \\"Sony PlayStation 4\\", \\"Sony PlayStation 5\\"], \\"brand\\": \\"THRUSTMASTER\\", \\"bundle\\": \\"Wheel + Pedals\\"}","sku":"106029190005200","connectivity":"{\\"wired\\": \\"Yes\\"}","stock":"2","price":"3399000 MNT","dimensions":"","index":"shop_386_1771211770","product_id":"698977503516dac1b3e97a6c","shop_name":"IT Store","discount":"{\\"regular_price\\": \\"3799000 MNT\\", \\"sale_price\\": \\"3399000 MNT\\"}","main_option":"{\\"connectivity\\": \\"Wired\\", \\"compatibility\\": \\"PC \\/ PS4 \\/ PS5\\", \\"bundle\\": \\"Wheel + Pedals\\", \\"color\\": \\"Black\\"}","details":"{\\"images\\": [\\"https:\\/\\/cdnp.cody.mn\\/spree\\/images\\/1719369\\/mini\\/_0000_T-GT-2-pack-racing-ps5-ps4-pc-768x768.png?1680689441\\", \\"https:\\/\\/cdnp.cody.mn\\/spree\\/images\\/1719373\\/mini\\/_0002_TGT2-ps4-ps5-pc_2.png?1680689454\\", \\"https:\\/\\/cdnp.cody.mn\\/spree\\/images\\/1719371\\/mini\\/_0001_T-GT-II-Pack-ps4-ps5-2-pichi.png?1680689448\\", \\"https:\\/\\/cdnp.cody.mn\\/spree\\/images\\/1719372\\/mini\\/_0002_Layer-2.png?1680689450\\", \\"https:\\/\\/cdnp.cody.mn\\/spree\\/images\\/1719368\\/mini\\/_0000_Layer-4.png?1680689438\\", \\"https:\\/\\/cdnp.cody.mn\\/spree\\/images\\/1719370\\/mini\\/_0001_Layer-3.png?1680689444\\"], \\"product_state\\": \\"NEW\\", \\"sync_state\\": \\"SYNCED\\", \\"created_at\\": \\"2026-02-09T05:57:36.956Z\\", \\"updated_at\\": \\"2026-02-09T05:57:36.956Z\\", \\"checksum\\": \\"97816fa8acf4f03f5069baa80502cd29c28289699130927a879be859134d974c\\"}","url_link":"https:\\/\\/cdnp.cody.mn\\/spree\\/images\\/1719369\\/mini\\/_0000_T-GT-2-pack-racing-ps5-ps4-pc-768x768.png?1680689441","keywords":"Thrustmaster, T-GT II, racing wheel, gaming wheel, wheel and pedals, PS5 wheel, PS4 wheel, PC racing controller","best_used_for":"Gaming","premium_grade":"premium","price_range":"high-end","insurance":"","delivery":"Pickup, Shipping","taxon_id":"69fbef9bda75a61ceadc7607","taxon_name":"video-game-racing-wheel","description":"connectivity: Wired\\ncompatibility: PC, Sony PlayStation 4, Sony PlayStation 5\\nbrand: THRUSTMASTER","best_used_for_detail":"Designed for racing simulation on PC and PlayStation (PS4\\/PS5); ideal for immersive driving and competitive racing experiences.","taxondict":"NaN","prompt_":"{\\"role\\": \\"user\\", \\"content\\": \\"product index : 386,\\\\n\'\'\'{\'PRODUCT_ID\': \'698977503516dac1b3e97a6c\', \'_ID_SHOP\': 2008428, \'CODYVARIANTID\': 1751098, \'NAME\': \'Thrustmaster T-GT II Wired Wheel And Pedals Set\', \'MAINPRICE\': 3799000, \'SALEPRICE\': 3399000, \'SKU\': \'106029190005200\', \'STOCK\': 2, \'IMAGE\': \'https:\\/\\/cdnp.cody.mn\\/spree\\/images\\/1719369\\/mini\\/_0000_T-GT-2-pack-racing-ps5-ps4-pc-768x768.png?1680689441\', \'IMAGES\': [\'https:\\/\\/cdnp.cody.mn\\/spree\\/images\\/1719369\\/mini\\/_0000_T-GT-2-pack-racing-ps5-ps4-pc-768x768.png?1680689441\', \'https:\\/\\/cdnp.cody.mn\\/spree\\/images\\/1719373\\/mini\\/_0002_TGT2-ps4-ps5-pc_2.png?1680689454\', \'https:\\/\\/cdnp.cody.mn\\/spree\\/images\\/1719371\\/mini\\/_0001_T-GT-II-Pack-ps4-ps5-2-pichi.png?1680689448\', \'https:\\/\\/cdnp.cody.mn\\/spree\\/images\\/1719372\\/mini\\/_0002_Layer-2.png?1680689450\', \'https:\\/\\/cdnp.cody.mn\\/spree\\/images\\/1719368\\/mini\\/_0000_Layer-4.png?1680689438\', \'https:\\/\\/cdnp.cody.mn\\/spree\\/images\\/1719370\\/mini\\/_0001_Layer-3.png?1680689444\'], \'SYNCSTATE\': \'SYNCED\', \'PRODUCTSTATE\': \'NEW\', \'DESCRIPTION\': \'connectivity: Wired\\\\\\\\ncompatibility: PC, Sony PlayStation 4, Sony PlayStation 5\\\\\\\\nbrand: THRUSTMASTER\', \'PROPERTY\': {\'connectivity\': \'Wired\', \'compatibility\': \'PC, Sony PlayStation 4, Sony PlayStation 5\', \'brand\': \'THRUSTMASTER\'}, \'VARIANTS\': [1751098], \'CREATEDAT\': \'2026-02-09T05:57:36.956Z\', \'UPDATEDAT\': \'2026-02-09T05:57:36.956Z\', \'CHECKSUM\': \'97816fa8acf4f03f5069baa80502cd29c28289699130927a879be859134d974c\', \'SHOP_NAME\': \'IT Store\'}\'\'\'\\"}","created_at":"2026-02-16 13:38:31.838743","colors":"NaN","image_list":null,"images":"NaN","mainoption":"NaN","data_relation_map":"NaN","color":null,"image":null,"productstate":null,"createdat":null,"updatedat":null,"productmeta":null,"saleprice":null,"image_urls":null,"details_translation":null,"group_id":"aefdaea2-f39c-52b6-9b47-a5410338e847"}]'

In [32]:
import pandas as pd
pd.set_option('display.max_columns', 100)

In [33]:
print(master_catalog_profile.head(2).to_json(orient="records"))

[{"carried_located_in":"Living Room","main_category":"Electronics","sub_category":"Televisions","product_category":"Mini LED QLED 4K TVs","exact_product_category":"Sony 85XR50 85-inch Mini LED QLED 4K HDR Google TV","manufacturer":"SONY","generic_name":"Smart Television","actual_product":"Mini LED QLED 4K HDR Google 85 inch tv \/SONY-K-85XR50\/","size":"85 inches","power_consumption":"","year":"2026","specifications":"{\"resolution\": \"UHD 4K 3840x2160p\", \"processor\": \"XR Processor (image enhancement AI)\", \"panel_type\": \"Mini LED QLED\", \"wide_viewing\": \"X-Wide Angle\", \"anti_reflection\": \"X-Anti Reflection\", \"operating_system\": \"ANDROID (Google TV)\", \"preinstalled_apps\": [\"Netflix\", \"Prime Video\", \"Disney+\", \"YouTube\", \"Apple TV\"], \"ai_image_enhancement\": \"Yes\", \"refresh_rate\": \"Motionflow\u2122 XR 800Hz (Native 120Hz)\", \"eye_protection\": \"Yes\", \"audio\": [\"Dolby Atmos\", \"DSEE\", \"Cinema\", \"X-Balanced Speaker\"], \"hdmi_ports\": 4, \"usb_ports\": 2, \"wifi\": \"Yes\", \"lan\": \"Yes\", \"bluetooth\": \"Yes\", \"dimensions_without_stand_mm\": \"1891 x 1085 x 492 (width x height x depth)\", \"dimensions_with_stand_mm\": \"1891 x 1120 x 464 (width x height x depth)\", \"weight_kg\": \"45\"}","sku":"SONY-K-85XR50","connectivity":"{\"wifi\": \"Yes\", \"bluetooth\": \"Yes\", \"hdmi\": \"4\", \"usb\": \"2\", \"lan\": \"Yes\"}","stock":"2","price":"11999900 MNT","dimensions":"Without stand: 1891 x 1085 x 492 mm; With stand: 1891 x 1120 x 464 mm","index":"shop_0_1772709420","product_id":"6968a70895de95f954a9a16c","shop_name":"BSB Electronics","discount":"{\"regular_price\": \"12999900 MNT\", \"sale_price\": \"11999900 MNT\", \"currency\": \"MNT\"}","main_option":"{\"screen-size\": \"85inch\", \"resolution\": \"3840x2160\", \"panel\": \"Mini LED QLED\", \"hdr\": \"HDR\", \"os\": \"Google TV\", \"refresh_rate\": \"Native 120Hz (Motionflow XR 800Hz)\", \"hdmi_ports\": \"4\", \"usb_ports\": \"2\", \"color\": \"\"}","details":"85-inch Sony Mini LED QLED 4K HDR Google TV with XR Processor, X-Wide Angle, X-Anti Reflection, Motionflow XR, Dolby Atmos and X-Balanced Speaker. Dimensions and weight provided. Android Google TV platform supports major streaming apps.","url_link":"https:\/\/imagedelivery.net\/jUCGGlEY6TCUtkJb-Fl1XA\/85\/77\/a8253d63f8ea73d4f9c45056ee35.jpg\/public","keywords":"[\"Sony TV\", \"85 inch TV\", \"Mini LED\", \"QLED\", \"4K TV\", \"Google TV\", \"Dolby Atmos\", \"XR Processor\"]","best_used_for":"Entertainment","premium_grade":"premium","price_range":"luxury","insurance":"","delivery":"Pickup, Shipping","taxon_id":"674425c2b07fff9ff4a48d4c","taxon_name":"tv","description":"Screen size: 85 inch Resolution: UHD 4K 3840x2160p XR Processor improves color and clarity for each scene X-Wide Angle and X-Anti Reflection allow color-accurate viewing from all angles Operating system: ANDROID Google TV \u2014 download favorite apps Netflix, Prime Video, Disney+, YouTube, Apple TV AI improves picture color Speed: Motionflow\u2122 XR 800Hz (Native 120Hz) Features: Eye protection Output: Dolby Atmos, DSEE, Cinema. X-Balanced Speaker Smart connectivity: Bluetooth, HDMIx4, USBx2, WiFi, LAN Dimensions without stand: 1891 x 1085 x 492 mm (width x height x depth) Dimensions with stand: 1891 x 1120 x 464 mm (width x height x depth) Weight: 45kg","best_used_for_detail":"Optimized for home entertainment and streaming, delivering high-fidelity audio and AI-enhanced 4K visuals for movies and TV shows.","taxondict":"NaN","prompt_":"{\"role\": \"user\", \"content\": \"product index : 0,\\n'''{'PRODUCT_ID': '6968a70895de95f954a9a16c', 'ID': 9480, 'BSBVARAINTID': 'SONY-K-85XR50', 'NAME': 'Mini LED QLED 4K HDR Google 85 \u0438\u043d\u0447 \u0442\u0432 \/SONY-K-85XR50\/', 'MAINPRICE': 12999900, 'SALEPRICE': 11999900, 'SKU': 'SONY-K-85XR50', 'STOCK': 2, 'IMAGE': 'https:\/\/imagedelivery.net\/jUCGGlEY6TCUtkJb-Fl1XA\/85\/77\/a8253d63f8ea73d4f9c45056ee35.jpg\/public', 'IMAGES': ['https:\/\/imagedelivery.net\/jUCGGlEY6TCUtkJb-Fl1XA\/85\/77\/a8253d63f8ea73d4f9c45056ee35.jpg\/public', 'https:\/\/imagedelivery.net\/jUCGGlEY6TCUtkJb-Fl1XA\/8a\/2f\/d2f97ff9a7c9f3cf3240facbdba2.jpg\/public', 'https:\/\/imagedelivery.net\/jUCGGlEY6TCUtkJb-Fl1XA\/20\/2e\/8eb4e09523ece25f6782d32c877f.jpg\/public', 'https:\/\/imagedelivery.net\/jUCGGlEY6TCUtkJb-Fl1XA\/d2\/b0\/a4f7344af4da327c45fb482afe1c.jpg\/public'], 'SYNCSTATE': 'SYNCED', 'PRODUCTSTATE': 'SETTLED', 'DESCRIPTION': '\u0414\u044d\u043b\u0433\u044d\u0446\u0438\u0439\u043d \u0445\u044d\u043c\u0436\u044d\u044d: 85 \u0438\u043d\u0447\u041d\u044f\u0433\u0442\u0440\u0430\u043b\u0448\u0438\u043b: UHD 4K 3840x2160pXR Processor \u043d\u044c \u04af\u0437\u044d\u0433\u0434\u044d\u043b \u0431\u04af\u0440\u0438\u0439\u0433 \u0442\u0443\u0445\u0430\u0439\u043d \u0446\u0430\u0433\u0442 \u043d\u044c \u04e9\u043d\u0433\u04e9 \u0442\u043e\u0434 \u0431\u0430\u0439\u0434\u043b\u044b\u0433 \u043d\u044c \u0443\u0445\u0430\u0430\u043b\u0433\u0430\u0430\u0440 \u0441\u0430\u0439\u0436\u0440\u0443\u0443\u043b\u0434\u0430\u0433X-Wide Angle \u0431\u043e\u043b\u043e\u043d X-Anti Reflection \u043d\u044c \u04e9\u0440\u04e9\u04e9\u043d\u0438\u0439 \u0431\u04af\u0445\u0438\u0439 \u043b \u0442\u0430\u043b\u0430\u0430\u0441 \u0434\u04af\u0440\u0441\u0438\u0439\u0433 \u04e9\u043d\u0433\u04e9 \u0430\u043b\u0434\u0430\u043b\u0442\u0433\u04af\u0439\u0433\u044d\u044d\u0440 \u0445\u0430\u0440\u0430\u0445 \u0431\u043e\u043b\u043e\u043c\u0436\u0442\u043e\u0439\\\\u200b\u04ae\u0439\u043b\u0434\u043b\u0438\u0439\u043d \u0441\u0438\u0441\u0442\u0435\u043c: ANDROID Google tv \u0430\u0448\u0438\u0433\u043b\u0430\u043d \u04e9\u04e9\u0440\u0438\u0439\u043d \u0434\u0443\u0440\u0442\u0430\u0439 \u0430\u043f\u043f\u0430\u0430 \u0442\u0430\u0442\u0430\u0445 \u0431\u043e\u043b\u043e\u043c\u0436\u0442\u043e\u0439\\\\u200bNetflix, Prime Video, Disney+, YouTube, Apple TV \u0433\u044d\u0445 \u043c\u044d\u0442 \u0434\u0443\u0440\u0442\u0430\u0439 \u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u04af\u0437\u044d\u044d\u0440\u044d\u0439\u0425\u0438\u0439\u043c\u044d\u043b \u043e\u044e\u0443\u043d \u0443\u0445\u0430\u0430\u043d\u0430\u0430\u0440 \u0434\u04af\u0440\u0441 \u04e9\u043d\u0433\u04e9 \u0441\u0430\u0439\u0436\u0440\u0443\u0443\u043b\u0434\u0430\u0433\u0425\u0443\u0440\u0434: Motionflow\u2122 XR 800Hz (Native 120Hz)\u041e\u043d\u0446\u043b\u043e\u0433 : \u041d\u04af\u0434\u043d\u0438\u0439 \u0445\u0430\u0440\u0430\u0430\u043d\u044b \u0445\u0430\u043c\u0433\u0430\u0430\u043b\u0430\u043b\u0442\u0442\u0430\u0439\u0414\u0443\u0433\u0430\u0440\u0430\u043b\u0442: Dolby Atmos, Dsee, Cinema. X-Blanced SpeakerSmart \u0445\u043e\u043b\u0431\u043e\u043b\u0442: Bluetooth, HDMIx4, USBx2, WiFi, LAN\u0421\u0443\u0443\u0440\u044c\u0433\u04af\u0439 \u0445\u044d\u043c\u0436\u044d\u044d 1891x1085x492\u043c\u043c (\u04e9\u0440\u0433\u04e9\u043d x \u04e9\u043d\u0434\u04e9\u0440 x \u0433\u04af\u043d)\u0421\u0443\u0443\u0440\u044c\u0442\u0430\u0439 \u0445\u044d\u043c\u0436\u044d\u044d 1891x1120x464\u043c\u043c (\u04e9\u0440\u0433\u04e9\u043d x \u04e9\u043d\u0434\u04e9\u0440 x \u0433\u04af\u043d)\u0416\u0438\u043d 45\u043a\u0433', 'CREATEDAT': '2026-01-15T08:36:24.251Z', 'UPDATEDAT': '2026-03-05T06:00:02.716Z', 'CHECKSUM': 'ba6877a2abe4137fbefa709a2ea14e93191ffae3943e03dd713285224f6a9b5d', 'SYNCEDAT': '2026-03-05T06:00:02.715Z', 'SHOP_NAME': 'BSB Electronics'}'''\"}","created_at":"2026-03-05 19:17:48.739441","colors":null,"image_list":null,"images":"NaN","mainoption":"NaN","data_relation_map":"NaN","color":null,"image":null,"productstate":null,"createdat":null,"updatedat":null,"productmeta":null,"saleprice":null,"image_urls":null,"details_translation":null,"group_id":"9769a9ad-9471-5347-abf4-c920d69a0e3e"},{"carried_located_in":"Living Room","main_category":"Electronics","sub_category":"Televisions","product_category":"4K UHD TVs","exact_product_category":"Full Array LED 4K HDR Smart TV","manufacturer":"Panasonic","generic_name":"Smart Television","actual_product":"Panasonic TH-75NX900","size":"75 inch","power_consumption":"","year":"2026","specifications":"{\"screen_type\": \"Full Array LED\", \"resolution\": \"3840 x 2160\", \"hdr\": \"4K HDR (Dolby Vision supported)\", \"operating_system\": \"Google TV\", \"refresh_rate\": \"120Hz\", \"processor\": \"4K Studio Colour Engine\", \"audio\": \"Dolby Atmos, Dolby Vision (video HDR), 624W speaker\", \"smart_features\": \"Media player, Internet apps (Netflix, Amazon, YouTube)\", \"voice_control\": \"Yes (Voice Control)\", \"connectivity_summary\": \"Screen sharing, Wi\u2011Fi, Bluetooth 5.1\", \"ports\": \"HDMI inputs 3 (HDMI 2.1), USB inputs 2\", \"dimensions_mm\": \"1675 x 1041 x 363 mm\", \"weight_without_stand\": \"35.5 kg\", \"color\": \"Black\"}","sku":"PANA-TH-75NX900M","connectivity":"{\"wifi\": \"Yes\", \"bluetooth\": \"Bluetooth 5.1\", \"screen_sharing\": \"Yes\", \"ethernet\": \"\", \"hdmi\": \"3 (HDMI 2.1)\", \"usb\": \"2\"}","stock":"1","price":"4599900 MNT","dimensions":"1675 x 1041 x 363 mm","index":"shop_1_1772709420","product_id":"6968a70895de95f954a9a16f","shop_name":"BSB Electronics","discount":"{\"regular_price\": \"5499900 MNT\", \"sale_price\": \"4599900 MNT\", \"discount_amount\": \"900000 MNT\", \"discount_percent\": \"16.36%\"}","main_option":"{\"screen-size\": \"75 inch\", \"resolution\": \"3840 x 2160\", \"refresh_rate\": \"120Hz\", \"operating_system\": \"Google TV\", \"processor\": \"4K Studio Colour Engine\", \"color\": \"Black\"}","details":"PRODUCTSTATE: ARCHIVED; SYNCSTATE: SYNCED; CREATEDAT: 2026-01-15T08:36:24.303Z; UPDATEDAT: 2026-03-05T06:00:03.272Z; IMAGES count: 5","url_link":"https:\/\/imagedelivery.net\/jUCGGlEY6TCUtkJb-Fl1XA\/58\/e0\/648d1ec6f8552640754f011bfd6e.jpg\/public","keywords":"[\"Panasonic\", \"Panasonic TH-75NX900\", \"75 inch TV\", \"4K UHD\", \"Full Array LED\", \"Google TV\", \"Dolby Vision\", \"Dolby Atmos\", \"Smart TV\", \"HDMI 2.1\"]","best_used_for":"Entertainment","premium_grade":"premium","price_range":"high-end","insurance":"","delivery":"Pickup","taxon_id":"674425c2b07fff9ff4a48d4c","taxon_name":"tv","description":"Screen size: 75 inch, 1675mm Screen: Full Array Led, 4K HDR Smart TV Resolution: 3840 x 2160 Operating system: Google TV Speed: 120hz Processor: 4K Studio Colour Engine Features: With media player, Internet app downloadable, Netflix, Amazon, Youtube Output sound: Dolby Vision, Dolby Atmos, 624W speaker, Voice Control or controlled by voice Smart connectivity: Screen sharing, Wi-Fi, Bluetooth 5.1 Cable connection: HDMI inputs 3pcs, HDMI 2.1, USB inputs 2pcs Size (width X height X depth mm): 1675 x 1041 x 363 mm Weight without stand: 35.5kg","best_used_for_detail":"Ideal for home entertainment and streaming (movies, series) with HDR video and immersive audio.","taxondict":"NaN","prompt_":"{\"role\": \"user\", \"content\": \"product index : 1,\\n'''{'PRODUCT_ID': '6968a70895de95f954a9a16f', 'ID': 9278, 'BSBVARAINTID': 'PANA-TH-75NX900M', 'NAME': 'Panasonic TH-75NX900  Full Array Led 75 \u0438\u043d\u0447\u0438\u0439\u043d \u0443\u0445\u0430\u0430\u043b\u0430\u0433 \u0437\u0443\u0440\u0430\u0433\u0442', 'MAINPRICE': 5499900, 'SALEPRICE': 4599900, 'SKU': 'PANA-TH-75NX900M', 'STOCK': 1, 'IMAGE': 'https:\/\/imagedelivery.net\/jUCGGlEY6TCUtkJb-Fl1XA\/58\/e0\/648d1ec6f8552640754f011bfd6e.jpg\/public', 'IMAGES': ['https:\/\/imagedelivery.net\/jUCGGlEY6TCUtkJb-Fl1XA\/58\/e0\/648d1ec6f8552640754f011bfd6e.jpg\/public', 'https:\/\/imagedelivery.net\/jUCGGlEY6TCUtkJb-Fl1XA\/0d\/06\/91b668a62a1bc1b9b25b7833159d.jpg\/public', 'https:\/\/imagedelivery.net\/jUCGGlEY6TCUtkJb-Fl1XA\/96\/d2\/0d2a626db95115faa376f759dffb.jpg\/public', 'https:\/\/imagedelivery.net\/jUCGGlEY6TCUtkJb-Fl1XA\/22\/e7\/eb2de2b476c2dd6c841c9713f125.jpg\/public', 'https:\/\/imagedelivery.net\/jUCGGlEY6TCUtkJb-Fl1XA\/aa\/cd\/cd8798db5baa961702b228946f85.jpg\/public'], 'SYNCSTATE': 'SYNCED', 'PRODUCTSTATE': 'ARCHIVED', 'DESCRIPTION': '\u0414\u044d\u043b\u0433\u044d\u0446\u0438\u0439\u043d \u0445\u044d\u043c\u0436\u044d\u044d: 75 \u0438\u043d\u0447, 1675\u043c\u043c\u0414\u044d\u043b\u0433\u044d\u0446: Full Array Led, 4K HDR Smart TV\\\\xa0\u041d\u044f\u0433\u0442\u0430\u0440\u0448\u0438\u043b: 3840 x 2160\u04ae\u0439\u043b\u0434\u043b\u0438\u0439\u043d \u0441\u0438\u0441\u0442\u0435\u043c: Google TV\u0425\u0443\u0440\u0434: 120hz\u041f\u0440\u043e\u0446\u0435\u0441\u0441\u043e\u0440: 4K Studio Colour Engine\\\\xa0\u041e\u043d\u0446\u043b\u043e\u0433: \u041c\u0435\u0434\u0438\u0430 \u0442\u043e\u0433\u043b\u0443\u0443\u043b\u0430\u0433\u0447\u0442\u0430\u0439,\\\\xa0\u0418\u043d\u0442\u0435\u0440\u043d\u044d\u0442 \u0430\u043f\u043f \u0442\u0430\u0442\u0430\u0433\u0434\u0430\u043d\u0430, Netflix, Amazon, Youtube\u0414\u0443\u0443\u0433\u0430\u0440\u0430\u043b\u0442: Dolby Vision, Dolby Atmos, 624W speaker,\\\\xa0Voice Control \u0431\u0443\u044e\u0443 \u0434\u0443\u0443 \u0445\u043e\u043e\u043b\u043e\u0439\u0433\u043e\u043e\u0440 \u0443\u0434\u0438\u0440\u0434\u0430\u043d\u0430Smart \u0445\u043e\u043b\u0431\u043e\u043b\u0442: Screen sharing, Wi-Fi, Bluethooth 5.1,\\\\xa0\u041a\u0430\u0431\u0435\u043b\u0438\u0439\u043d \u0445\u043e\u043b\u0431\u043e\u043b\u0442: HDMI \u043e\u0440\u043e\u043b\u0442 3\u0448, HDMI 2.1, USB \u043e\u0440\u043e\u043b\u0442 2\u0448,\\\\xa0\\\\xa0\u0425\u044d\u043c\u0436\u044d\u044d (\u04e9\u0440\u0433\u04e9\u043d \u0425 \u04e9\u043d\u0434\u04e9\u0440 \u0425 \u0433\u04af\u043d \u043c\u043c): 1675 \u0445 1041 \u0445 363 \u043c\u043c\u0421\u0443\u0443\u0440\u044c\u0433\u04af\u0439 \u0436\u0438\u043d: 35,5\u043a\u0433', 'CREATEDAT': '2026-01-15T08:36:24.303Z', 'UPDATEDAT': '2026-03-05T06:00:03.272Z', 'CHECKSUM': '97d2cf3fff0e8d0938292ffa8b260e1b4356e91c9b63465c0f0ba3759707e6eb', 'SYNCEDAT': '2026-03-05T06:00:03.097Z', 'SHOP_NAME': 'BSB Electronics'}'''\"}","created_at":"2026-03-05 19:18:43.058787","colors":null,"image_list":null,"images":"NaN","mainoption":"NaN","data_relation_map":"NaN","color":null,"image":null,"productstate":null,"createdat":null,"updatedat":null,"productmeta":null,"saleprice":null,"image_urls":null,"details_translation":null,"group_id":"eae2fd2c-1c51-56f4-a7ec-7561dbfd11e9"}]

## Recommendation Engine — Live API Integration

The engine is running on **port 8018** (local) and publicly via Cloudflare Tunnel.

### Available endpoints
| Endpoint | Method | Purpose |
|---|---|---|
| `/api/v1/events` | POST | Ingest `customer_activities` events (order, cart, limit, wishlist, view, product_click, taxon_click) |
| `/api/v1/consumer-events` | POST | Ingest Oracle `consumer_events` rows directly (EVENTNAME, EVENTVALUE, ACCOUNTID …) |
| `/api/v1/infer` | POST | On-demand single-taxon inference for a user |
| `/api/v1/feed` | POST | Multi-taxon feed — returns top-N products per taxon based on interaction scores |
| `/api/v1/feed/push` | POST | Generate feed AND push it to the shop's API endpoint |
| `/api/v1/health` | GET | Liveness check |
| `/api/v1/catalog/status` | GET | Catalog index stats |

### Feed response format (shop receives)
```json
{
  "id": "<account_id>",
  "taxon_feeds": [
    { "taxon_id": "69fb126eae2e0da5c8bca3a0", "taxon_name": "household-appliances-multi-purpose-vacuum", "recommendations": ["pid1", "pid2", ...] },
    { "taxon_id": "69fbef9bda75a61ceadc7607", "taxon_name": "video-game-racing-wheel", "recommendations": ["pid3", "pid4", ...] }
  ],
  "total_products": 24,
  "strategy": "multi_taxon_hybrid",
  "intent_score": 9.5
}
```

In [ ]:
import requests, json

BASE = "http://localhost:8018"

# ── Catalog status ─────────────────────────────────────────────────────────────
status = requests.get(f"{BASE}/api/v1/catalog/status").json()
print(f"Catalog: {status['catalog_size']} products | TF-IDF {status['tfidf_shape']}")
print(f"Taxon labels mapped: {status['taxon_label_map_size']} | Taxon slugs: {status['taxon_name_map_size']}")
print(f"Active sessions: {status['active_sessions']} | Tracked users: {status['tracked_users']}")

In [ ]:
# ── POST /consumer-events: ingest real Oracle consumer_events rows ─────────────
# Simulates batch rows exactly as they appear in the Oracle table (uppercase field names)

sample_consumer_rows = [
    {
        "ID_": "6a44ce39ce31add3c347e3d6",
        "EVENTNAME": "product_click",
        "EVENTVALUE": "{'productIds': ['69fc469bab34c8d11412ec79'], 'taxon': {'label': '\u04ae\u0441\u043d\u0438\u0439 \u0445\u044d\u0440\u044d\u0433\u0441\u044d\u043b'}}",
        "ACCOUNTID": "66fbc5824e022311128232ae",
        "SESSIONID": "jPAaTyDWFjD1JsHyR0ux3hewNYRvNvRy",
        "TIMESTAMP_": "2026-07-01T08:21:23.894Z",
        "USERAGENT": "Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15",
    },
    {
        "ID_": "6a44ce3b420fe633e02e2e78",
        "EVENTNAME": "taxon_click",
        "EVENTVALUE": "{'taxon': {'label': '\u0413\u0430\u0440 \u0443\u0442\u0430\u0441'}}",
        "ACCOUNTID": "5ff870ee4f636263bd482270",
        "SESSIONID": "2xI3rxpGJbBOeY4vnY_1EBSkTuAL8Pf9",
        "TIMESTAMP_": "2026-07-01T08:22:19.413Z",
        "USERAGENT": "Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15",
    },
]

r = requests.post(f"{BASE}/api/v1/consumer-events", json={"events": sample_consumer_rows})
result = r.json()
print(f"Status: {result['status']} | processed={result['processed']} failed={result['failed']}")
print()
for rec in result["recommendations"]:
    print(f"  user: {rec['id']}")
    print(f"  taxon_id: {rec['taxon_id']}")
    print(f"  strategy: {rec['strategy']} | intent: {rec['intent_score']} | device: {rec['device']}")
    print(f"  recs ({rec['count']}): {rec['recommendations'][:4]}...")
    print()

In [ ]:
# ── POST /feed: multi-taxon recommendations ────────────────────────────────────
# Build up a user's history first, then generate a multi-taxon feed

# Simulate user history: viewed vacuum, ordered racing wheel, wishlisted Dyson
requests.post(f"{BASE}/api/v1/events", json={"events": [
    {"account_id": "demo_user_001", "activity_name": "product_click",
     "activity_data": {"productIds": ["69fc469bab34c8d11412ec79"], "taxon": {"label": "household-appliances-multi-purpose-vacuum"}}},
    {"account_id": "demo_user_001", "activity_name": "order-events",
     "activity_data": {"accountid": "demo_user_001", "productid": "698977503516dac1b3e97a6c", "action": "complete"}},
    {"account_id": "demo_user_001", "activity_name": "limit-events",
     "activity_data": {"accountid": "demo_user_001", "limit_amount": 3000000, "currency": "MNT"}},
    {"account_id": "demo_user_001", "activity_name": "wishlist-events",
     "activity_data": {"accountid": "demo_user_001", "productid": "6a309f8bd46aca65f8084431", "action": "add"}},
]})

# Now request multi-taxon feed
r = requests.post(f"{BASE}/api/v1/feed", json={
    "account_id": "demo_user_001",
    "top_taxons": 3,
    "top_n_per_taxon": 8,
})
feed = r.json()
print(f"Strategy: {feed['strategy']} | Intent: {feed['intent_score']} | Total products: {feed['total_products']}")
print()
for tf in feed["taxon_feeds"]:
    print(f"  [{tf['taxon_name']}]")
    print(f"   taxon_id: {tf['taxon_id']}")
    print(f"   recommendations ({tf['count']}): {tf['recommendations'][:4]}...")
    print()

In [ ]:
# ── POST /feed/push: push feed to shop's API ───────────────────────────────────
# Change `shop_feed_url` to your shop's actual endpoint.
# Push payload: {"id": account_id, "taxon_feeds": [{taxon_id, taxon_name, recommendations}]}

SHOP_FEED_URL = "https://your-shop.example.com/api/recommendations"  # replace with real URL

r = requests.post(f"{BASE}/api/v1/feed/push", json={
    "account_id": "demo_user_001",
    "top_taxons": 3,
    "top_n_per_taxon": 10,
    "shop_feed_url": SHOP_FEED_URL,  # set to None to use config.MARKETPLACE_API_BASE_URL
    "push_timeout_seconds": 3.0,
})
push_result = r.json()
print(f"Strategy: {push_result['strategy']} | Total products: {push_result['total_products']}")
print(f"Push status: {push_result['push_status']} | Push URL: {push_result['push_url']}")
if push_result["push_error"]:
    print(f"Push error: {push_result['push_error']}")
print()
for tf in push_result["taxon_feeds"]:
    print(f"  {tf['taxon_name'] or tf['taxon_id']}: {tf['count']} products")

In [ ]:
# ── Public URL (internet-exposed via Cloudflare Tunnel) ───────────────────────
# Share this URL with shop developers for testing
PUBLIC_URL = "https://alerts-anti-renaissance-harvey.trycloudflare.com"

print("=== Public API endpoints for shop developers ===")
print()
print(f"Docs/Swagger UI:   {PUBLIC_URL}/docs")
print(f"Health check:      GET  {PUBLIC_URL}/api/v1/health")
print(f"Catalog status:    GET  {PUBLIC_URL}/api/v1/catalog/status")
print()
print(f"Ingest events:     POST {PUBLIC_URL}/api/v1/events")
print(f"Consumer events:   POST {PUBLIC_URL}/api/v1/consumer-events")
print(f"Single-taxon infer:POST {PUBLIC_URL}/api/v1/infer")
print(f"Multi-taxon feed:  POST {PUBLIC_URL}/api/v1/feed")
print(f"Feed + push back:  POST {PUBLIC_URL}/api/v1/feed/push")
print()

# Quick health check via public URL
import requests
r = requests.get(f"{PUBLIC_URL}/api/v1/health", timeout=10)
print(f"Public health check: {r.status_code} | catalog_ready={r.json()['catalog_ready']}")